version: 2

references:
  ng_container: &ng_container
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
  restore_cache: &restore_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
  install_deps: &install_deps
    run:
      name: Install Dependencies
      command: npm install
  save_cache: &save_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}
  add_keys: &add_keys
    add_ssh_keys:
      fingerprints:
        - "a7:15:22:45:e7:c1:b7:87:bf:77:3b:4c:a7:4c:b4:77"
  config_keys: &config_keys
    run:
      name: Config Keys
      command: |
        sudo apt install rsync
        ssh-keyscan -H r3.richnologies.io >> ~/.ssh/known_hosts
        chmod 400 ~/.ssh/id_rsa_a7152245e7c1b787bf773b4ca74cb477

jobs:
  ngx-stripe-tester:
    <<: *ng_container
    steps:
      - checkout
      - *install_deps
      - *add_keys
      - *config_keys
      - run:
          name: Build
          command: npm run build:app
      - run:
          name: Deploy
          command: |
            rsync -av --delete ~/repo/dist/ngx-stripe-tester/ -e "ssh -oStrictHostKeyChecking=no -i ~/.ssh/id_rsa_a7152245e7c1b787bf773b4ca74cb477" ubuntu@r3.richnologies.io:/home/ubuntu/ngx-stripe/ngx-stripe-tester
workflows:
  version: 2
  build:
    jobs:
      - ngx-stripe-tester:
          filters:
            branches:
              only: /^docs$/
